# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Serialization

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Speaker(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Speaker()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSpeaker(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Speaker
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Speaker
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Speaker
    def SpeakerID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MCSpeechToText.Transcript.Serialization.Guid import Guid
            obj = Guid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(2)
def SpeakerStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def SpeakerAddName(builder, name):
    """This method is deprecated. Please switch to AddName."""
    return AddName(builder, name)
def AddSpeakerID(builder, speakerID): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(speakerID), 0)
def SpeakerAddSpeakerID(builder, speakerID):
    """This method is deprecated. Please switch to AddSpeakerID."""
    return AddSpeakerID(builder, speakerID)
def End(builder): return builder.EndObject()
def SpeakerEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)