# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Serialization

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TranscriptDocument(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TranscriptDocument()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTranscriptDocument(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TranscriptDocument
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TranscriptDocument
    def TranscriptData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MCSpeechToText.Transcript.Serialization.TranscriptData import TranscriptData
            obj = TranscriptData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(1)
def TranscriptDocumentStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddTranscriptData(builder, transcriptData): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(transcriptData), 0)
def TranscriptDocumentAddTranscriptData(builder, transcriptData):
    """This method is deprecated. Please switch to AddTranscriptData."""
    return AddTranscriptData(builder, transcriptData)
def End(builder): return builder.EndObject()
def TranscriptDocumentEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)